### ISSUE TITLE
Compilation error when updating to angular 9.1.5

### ISSUE THREAD

**Issue by cedricduffournet** [angulartics/angulartics2#380]
**For support questions, please consider using [Gitter - Chat](https://gitter.im/angulartics/angulartics2)**

**I'm submitting a ...**

* [x] bug report  
* [ ] feature request  
* [ ] question about the decisions made in the repository

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
When updating angular to 9.1.5 I have the following error : 

```
ERROR in node_modules/angulartics2/public_api.d.ts:5:54 - error TS1149: File name '/Users/noname/Sites/angulartics2-error/node_modules/angulartics2/angulartics2On.d.ts' differs from already included file name '/Users/noname/Sites/angulartics2-error/node_modules/angulartics2/angulartics2on.d.ts' only in casing.

5 export { Angulartics2On, Angulartics2OnModule } from './angulartics2On';
```
You can file an example here: https://github.com/cedricduffournet/angulartics-error

* **What is the expected behavior?**
Should compile correctly

* **Environment:**

```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.4
Node: 13.11.0
OS: darwin x64

Angular: 9.1.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.4
@angular-devkit/build-angular     0.901.4
@angular-devkit/build-optimizer   0.901.4
@angular-devkit/build-webpack     0.901.4
@angular-devkit/core              9.1.4
@angular-devkit/schematics        9.1.4
@angular/cli                      9.1.4
@ngtools/webpack                  9.1.4
@schematics/angular               9.1.4
@schematics/update                0.901.4
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
```

**Comment by petebacondarwin** [comment]
This is a bug in ngcc. Working on a fix. See https://github.com/angular/angular/issues/36992#issuecomment-625758011

**Comment by cedricduffournet** [comment]
Thank you for the quick answer

**Comment by petebacondarwin** [comment]
I can confirm that https://github.com/angular/angular/pull/37008 fixes this locally for me.
